import './globals.css'
import { Inter, Lato, Open_Sans } from 'next/font/google'

const inter = Inter({ subsets: ['latin'] })

const lato = Lato({
  subsets: ["latin"],
  variable: "--font-lato",
  weight: '400'
})

const openSans = Open_Sans({
  subsets: ["latin"],
  variable: "--font-open-sans",
  weight: '300'
})


export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={`${inter.className} ${lato.variable} ${openSans.variable}`}>{children}</body>
    </html>
  )
}
